# Generated by Django 4.0 on 2022-01-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('n_greedy', models.IntegerField()),
                ('n_optimizing', models.IntegerField()),
                ('n_center', models.IntegerField()),
                ('distribution_choice', models.CharField(choices=[('N', 'Normal'), ('U', 'Uniform')], default='N', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'User Parameters for the Voting Model',
            },
        ),
    ]
